"""Modify inference table.

Add deployment_id column.

Revision ID: f38bf5afddc3
Revises: 177be8b49f13
Create Date: 2025-11-03 15:45:11.268456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38bf5afddc3'
down_revision: Union[str, Sequence[str], None] = '177be8b49f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inference', sa.Column(
        'deployment_id', sa.Integer(), nullable=False))
    op.create_index(
        op.f('ix_inference_deployment_id'),
        'inference',
        ['deployment_id'],
        unique=False
    )
    op.create_foreign_key(
        op.f('fk_inference_deployment_id_deployment'),
        'inference',
        'deployment',
        ['deployment_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('fk_inference_deployment_id_deployment'),
        'inference',
        type_='foreignkey'
    )
    op.drop_index(op.f('ix_inference_deployment_id'), table_name='inference')
    op.drop_column('inference', 'deployment_id')
    # ### end Alembic commands ###
