"""Add night_session column to devicetype.

Also renames the inference.date column to session_date.

Revision ID: 28b7fe4253cc
Revises: f38bf5afddc3
Create Date: 2025-11-04 15:19:45.265916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b7fe4253cc'
down_revision: Union[str, Sequence[str], None] = 'f38bf5afddc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column(
            'devicetype',
            sa.Column(
                'night_session',
                sa.Boolean(),
                server_default=sa.text('true'),
                nullable=False
            )
        )
        op.alter_column('inference', 'date', new_column_name='session_date')
        op.create_index(
            op.f('ix_inference_session_date'),
            'inference',
            ['session_date'],
            unique=False
        )
    except Exception as e:
        print(f"Error upgrading to {revision}: {e}")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_session_date'), table_name='inference')
    op.alter_column('inference', 'session_date', new_column_name='date')
    op.drop_column('devicetype', 'night_session')
    # ### end Alembic commands ###
