"""Modify inference table.

Replace deployment_id with device_id column.

Revision ID: 177be8b49f13
Revises: c4f54844b4de
Create Date: 2025-10-27 16:35:03.550009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlmodel.sql import sqltypes


# revision identifiers, used by Alembic.
revision: str = '177be8b49f13'
down_revision: Union[str, Sequence[str], None] = 'c4f54844b4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column(
            'inference',
            sa.Column('device_id', sqltypes.AutoString(), nullable=False)
        )
        op.drop_index(op.f('ix_inference_deployment_id'),
                      table_name='inference')
        op.create_index(
            op.f('ix_inference_device_id'),
            'inference',
            ['device_id'],
            unique=False
        )
        op.drop_constraint(
            op.f('fk_inference_deployment_id_deployment'),
            'inference',
            type_='foreignkey'
        )
        op.create_foreign_key(
            op.f('fk_inference_device_id_device'),
            'inference',
            'device',
            ['device_id'],
            ['id']
        )
        op.drop_column('inference', 'deployment_id')
    except Exception as e:
        print(f"Failed to upgrade inference table: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'inference',
        sa.Column('deployment_id', sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f('fk_inference_device_id_device'),
        'inference',
        type_='foreignkey'
    )
    op.create_foreign_key(
        op.f('fk_inference_deployment_id_deployment'),
        'inference',
        'deployment',
        ['deployment_id'],
        ['id']
    )
    op.drop_index(op.f('ix_inference_device_id'), table_name='inference')
    op.create_index(
        op.f('ix_inference_deployment_id'),
        'inference',
        ['deployment_id'],
        unique=False
    )
    op.drop_column('inference', 'device_id')
    # ### end Alembic commands ###
